-- Run this script in Oracle SQL Developer to create the necessary tables.

CREATE TABLE Users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    email VARCHAR2(255) UNIQUE NOT NULL,
    password VARCHAR2(255) NOT NULL,
    role VARCHAR2(50) DEFAULT 'user' CHECK (role IN ('user', 'admin')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Events (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(255) NOT NULL,
    description CLOB NOT NULL,
    event_date DATE NOT NULL,
    event_time VARCHAR2(50) NOT NULL,
    venue VARCHAR2(255) NOT NULL,
    category VARCHAR2(100) NOT NULL CHECK (category IN ('Corporate', 'Weddings', 'Concerts', 'Seminars', 'Parties', 'Other')),
    price NUMBER DEFAULT 0,
    image_url VARCHAR2(500) DEFAULT 'images/event_corporate.png',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Registrations (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    event_id NUMBER NOT NULL,
    guests NUMBER DEFAULT 1 CHECK (guests BETWEEN 1 AND 10),
    special_requirements VARCHAR2(1000),
    status VARCHAR2(50) DEFAULT 'Confirmed' CHECK (status IN ('Pending', 'Confirmed', 'Cancelled')),
    payment_method VARCHAR2(50) DEFAULT 'cc' CHECK (payment_method IN ('cc', 'paypal', 'bank')),
    registered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE,
    CONSTRAINT fk_event FOREIGN KEY (event_id) REFERENCES Events(id) ON DELETE CASCADE,
    CONSTRAINT unique_registration UNIQUE (user_id, event_id)
);

select * from Events;
























